# Generated by Django 2.1.2 on 2018-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
