# Generated by Django 2.1.2 on 2018-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_money',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
