# Generated by Django 2.1.2 on 2018-10-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='user',
            new_name='volunteer',
        ),
    ]
