# Generated by Django 2.1.2 on 2018-10-17 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20181017_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
