# Generated by Django 2.1.2 on 2018-10-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181026_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
