# Generated by Django 2.1.2 on 2018-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181026_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
