# Generated by Django 2.1.2 on 2018-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Vehicles', models.CharField(max_length=1000)),
                ('Water', models.IntegerField()),
                ('Packets_of_FoodItems', models.IntegerField()),
                ('Medicines', models.CharField(max_length=10000)),
                ('Date', models.DateField()),
            ],
        ),
    ]
